/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.entities.Categoria;
import services.CategoriaService;
import services.impl.CategoriaServiceImpl;

/**
 *
 * @author ELIAS
 */
public class frmCategoria extends javax.swing.JInternalFrame {
    
    //1 insert , 2 update
   private short accion=0;
    /**
     * Creates new form frmCategoria
     */
    public frmCategoria() {
        initComponents();
        ListarCategorias();
    }
    
    
    private void ListarCategorias(){
          DefaultTableModel dtm = (DefaultTableModel) tblcat.getModel();
        //si esta llena la tabla se borra
        if (tblcat.getRowCount()>0) {
            
                for (int i = tblcat.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
             }
            
        }
        
        CategoriaService categoriaService = new CategoriaServiceImpl();
        List<Categoria> categorias = categoriaService.listar();
         for (Integer count = 0; count < categorias.size(); count++){
             dtm.addRow(new Object[]{
                categorias.get(count).getCategoria_id(),
                categorias.get(count).getCategoria_categoriaid(),
                categorias.get(count).getCategoria_nombre()
            });
             
         }
    }
    
    private void EstadoBotones(boolean estado){
        
    cmdnuevo.setEnabled(estado);
    cmdcancelar.setEnabled(!estado);
    cmdguardar.setEnabled(!estado);
    cmdeditar.setEnabled(estado);
    cmdsalir.setEnabled(estado);
    txtnombre.setEditable(!estado);
    tblcat.setEnabled(estado);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblcat = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        cmdnuevo = new javax.swing.JButton();
        cmdguardar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalir = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Categorias");

        tblcat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CATEGORIA_ID", "CATEGORIA_CAT_ID", "NOMBRE"
            }
        ));
        tblcat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblcat);

        jToolBar1.setRollover(true);

        cmdnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_add.png"))); // NOI18N
        cmdnuevo.setText("Nuevo");
        cmdnuevo.setFocusable(false);
        cmdnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdnuevo);

        cmdguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/disk_save.png"))); // NOI18N
        cmdguardar.setText("Guardar");
        cmdguardar.setEnabled(false);
        cmdguardar.setFocusable(false);
        cmdguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdguardar);

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Cancel (2).png"))); // NOI18N
        cmdcancelar.setText("Cancelar");
        cmdcancelar.setEnabled(false);
        cmdcancelar.setFocusable(false);
        cmdcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdcancelar);

        cmdeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_edit.png"))); // NOI18N
        cmdeditar.setText("Editar");
        cmdeditar.setFocusable(false);
        cmdeditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdeditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdeditar);

        cmdsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door_in.png"))); // NOI18N
        cmdsalir.setText("Salir");
        cmdsalir.setFocusable(false);
        cmdsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdsalir);

        txtnombre.setEditable(false);

        jLabel1.setText("Nombre de la categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtnombre))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnuevoActionPerformed
        // TODO add your handling code here:
       //1 insert , 2 update
        accion=1;
        txtnombre.setText("");
        EstadoBotones(false);
    }//GEN-LAST:event_cmdnuevoActionPerformed

    private void cmdguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdguardarActionPerformed
        // TODO add your handling code here:
        //accion: 1 insert, 2 update
        if (accion==1) {
            if (txtnombre.getText().length() > 0) {
                EstadoBotones(true);
                Categoria categoria=new Categoria();
                categoria.setCategoria_nombre(txtnombre.getText());
                CategoriaService categoriaService = new CategoriaServiceImpl();
                categoriaService.crear(categoria);
                JOptionPane.showMessageDialog(rootPane, "Se registro correctamente", "Registro de categoria", JOptionPane.INFORMATION_MESSAGE, frameIcon);
                txtnombre.setText("");
                ListarCategorias();

            }else{

                JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre para la categoria", "Registro de categoria", JOptionPane.ERROR_MESSAGE, frameIcon);

            }
        
        } else if(accion==2){
            
            int fila=tblcat.getSelectedRow();
            if (txtnombre.getText().length() > 0) {
                EstadoBotones(true);
                Categoria categoria=new Categoria();
                categoria.setCategoria_id( Integer.parseInt( tblcat.getValueAt(fila,0).toString()));
                categoria.setCategoria_nombre(txtnombre.getText());
                CategoriaService categoriaService = new CategoriaServiceImpl();
                categoriaService.update(categoria);
                JOptionPane.showMessageDialog(rootPane, "Registro actualizado correctamente", "Registro de categoria", JOptionPane.INFORMATION_MESSAGE, frameIcon);
                txtnombre.setText("");
                ListarCategorias();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre para la categoria", "Registro de categoria", JOptionPane.ERROR_MESSAGE, frameIcon);
            }
            
        }
        
     
         
     
    }//GEN-LAST:event_cmdguardarActionPerformed

    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
      EstadoBotones(true);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // TODO add your handling code here:
        //accion: 1 insert , 2 update
          accion=2;
         EstadoBotones(false);
       

    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalirActionPerformed
     this.dispose();
    }//GEN-LAST:event_cmdsalirActionPerformed

    private void tblcatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcatMouseClicked
        // TODO add your handling code here:
          
         int fila=tblcat.getSelectedRow();
         
        String categoria= tblcat.getValueAt(fila,2).toString();
        txtnombre.setText(categoria);
        
    }//GEN-LAST:event_tblcatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdguardar;
    private javax.swing.JButton cmdnuevo;
    private javax.swing.JButton cmdsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblcat;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
