package views;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Queue;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.entities.DetalleCliente;
import models.entities.Pedido;
import models.entities.PedidoConProducto;
import services.impl.PedidoConProductoServiceImpl;
import utils.DBConn;

public class frmListaPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListaPedidos
     */
    public frmListaPedidos() {
        initComponents();
        dtfecha.setDateFormatString("dd/MM/yyyy");
        
        JTextFieldDateEditor editor = (JTextFieldDateEditor) dtfecha.getDateEditor();
        editor.setEditable(false);
        
         Date fecha = new Date();
         dtfecha.setDate(fecha);
        CargarPedidos();
        
        btn1.setVisible(false);
        btn2.setVisible(false);

    }

    private void CargarPedidos() {
         DefaultTableModel dtm = (DefaultTableModel) jpedidos.getModel();
         
           if (jpedidos.getRowCount()>0) {
            
                for (int i = jpedidos.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
             }
            
        }
        
        PedidoConProductoServiceImpl productoService = new PedidoConProductoServiceImpl();
        List<PedidoConProducto> pedidos = productoService.listar();
//
        for (Integer count = 0; count < pedidos.size(); count++) {
           // System.out.println(pedidos.get(count).getProducto_nombre());
           dtm.addRow(new Object[]{
                pedidos.get(count).getPedido_fecha(),
                pedidos.get(count).getPedido_orden(),
                pedidos.get(count).getCliente(),
                  pedidos.get(count).getProducto_precio(),
           
            });
        }
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpedidos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        dtfecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PEDIDOS");

        jpedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "ORDEN", "CLIENTE", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jpedidos);

        jToolBar1.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_add.png"))); // NOI18N
        jButton4.setText("Nuevo Pedido");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_refresh.png"))); // NOI18N
        jButton5.setText("Ordenar cola");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door_in.png"))); // NOI18N
        jButton6.setText("Salir");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_find.png"))); // NOI18N
        jButton1.setText("Ver Detalle");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ver1.png"))); // NOI18N
        jButton2.setText("Refrescar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        btn2.setText("Ordenar aplicando prioridad");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn2);

        btn1.setText("Nuevo Pedido");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btn1);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Fecha");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/find.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dtfecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        frmPedido pedido = new frmPedido();
        pedido.setVisible(true);
    }//GEN-LAST:event_btn1ActionPerformed
    
    private void ColaPrioritaria(){
        
        Pedido pedido = new Pedido();
        Queue<Pedido> ColaConPrioridad = new PriorityQueue<>(pedido.ReglasDelNegocio);

        int orden = 0;
        String cliente = "";
        int edadcliente = 0;
        String membresia = "";
        int productos = 0;
        double totalpedido;
        //Pedido(int orden, String cliente, int edadcliente, String membresia, int productos, double totalpedido)

        for (int i = 0; i < jpedidos.getRowCount(); i++) {

            orden = Integer.parseInt(jpedidos.getValueAt(i, 0).toString());
            cliente = jpedidos.getValueAt(i, 1).toString();
            edadcliente = Integer.parseInt(jpedidos.getValueAt(i, 2).toString());
            membresia = jpedidos.getValueAt(i, 3).toString();
            productos = Integer.parseInt(jpedidos.getValueAt(i, 4).toString());
            totalpedido = Double.parseDouble(jpedidos.getValueAt(i, 5).toString());

            Pedido pedidod = new Pedido(orden, cliente, edadcliente, membresia, productos, totalpedido);
            ColaConPrioridad.add(pedidod);

        }
        // SE LIMPIA LA TABLA PARA REORDENAR LOS PEDIDOS

        JOptionPane.showMessageDialog(rootPane, "limpia tabla");

        DefaultTableModel dtm = (DefaultTableModel) jpedidos.getModel();
        // SE VUELVE A LLENAR LA TABLA 
        String[] fila = new String[6];

        while (!ColaConPrioridad.isEmpty()) {

            Pedido ColaAtendida = ColaConPrioridad.poll();

            fila[0] = String.valueOf(ColaAtendida.getOrden());
            fila[1] = ColaAtendida.getCliente();
            fila[2] = String.valueOf(ColaAtendida.getEdadcliente());
            fila[3] = String.valueOf(ColaAtendida.getMembresiaCliente());
            fila[4] = String.valueOf(ColaAtendida.getProductos());
            fila[5] = String.valueOf(ColaAtendida.getTotalpedido());
            dtm.addRow(fila);

        }

        //UNA VEZ ATENDIDA LA COLA SE ELIMINA
        ColaConPrioridad.clear();


    }
    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Frame frame=JOptionPane.getFrameForComponent(this);
        frmNuevoPedido pedido=new frmNuevoPedido(frame,true);
        pedido.setLocationRelativeTo(this);
       
        pedido.setVisible(true);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VerDetalle();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           CargarPedidos();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void LimpiarTabla() {
        //se limpia la tabla para volver a llenar con la lista ordenada

        DefaultTableModel dtm = (DefaultTableModel) jpedidos.getModel();

        for (int i = jpedidos.getRowCount() - 1; i >= 0; i--) {
            dtm.removeRow(i);
        }
        //lblitems.setText(String.valueOf(tblProductos.getRowCount()));
    }
    
    private void VerDetalle(){
        
         HashMap<Integer,DetalleCliente> map= new  HashMap<Integer,DetalleCliente>();
          Connection connection = DBConn.getConnection();
          ResultSet resultSet;
          
          
        Frame frame=JOptionPane.getFrameForComponent(this);
        frmDetallePedido detallepedido=new frmDetallePedido(frame,true);
       
         DefaultTableModel dtm = (DefaultTableModel) detallepedido.tbldetalle.getModel();
          int idpedido=0;
          int fila=jpedidos.getSelectedRow();
         
          idpedido= Integer.parseInt(jpedidos.getValueAt(fila,1).toString()) ;
          DetalleCliente detalle;
          
        try {
             CallableStatement callableStatement = connection.prepareCall("{CALL sp_find_Detallepedido(?)}");
             callableStatement.setInt(1,idpedido);
             resultSet = callableStatement.executeQuery();
              while (resultSet.next()) {
                  int producto_id=resultSet.getInt(1);
                  String producto=resultSet.getString(2);
                  int cantidad=resultSet.getInt(3);
                  double precio=resultSet.getDouble(4);
                  
                  detalle =new DetalleCliente(producto_id,producto,cantidad,precio);
                  map.put(producto_id, detalle);
              }
              
              for(int i : map.keySet()){
                  
                  DetalleCliente det=map.get(i);
                                     
                    dtm.addRow(new Object[]{
                    det.getProducto_id(),
                    det.getProducto(),
                    det.getCantidad(),
                    det.getPrecio()
            });
             
              }
          
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
        
      
        detallepedido.setLocationRelativeTo(this);
        detallepedido.setVisible(true);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListaPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private com.toedter.calendar.JDateChooser dtfecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    public static javax.swing.JTable jpedidos;
    // End of variables declaration//GEN-END:variables
}
