/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import models.entities.ClaveRender;
import models.entities.Usuario;
import services.UsuarioService;
import services.impl.UsuarioServiceImpl;

/**
 *
 * @author ELIAS
 */
public class frmUsuarios extends javax.swing.JInternalFrame {
   int accion=0;
    /**
     * Creates new form frmUsuarios
     */
    public frmUsuarios() {
        initComponents();
        ListarUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmdnuevo = new javax.swing.JButton();
        cmdguardar = new javax.swing.JButton();
        cmdcancelar = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblusuario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtpass2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Usuarios");

        jToolBar1.setRollover(true);

        cmdnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_add.png"))); // NOI18N
        cmdnuevo.setText("Nuevo");
        cmdnuevo.setFocusable(false);
        cmdnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdnuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdnuevo);

        cmdguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/disk_save.png"))); // NOI18N
        cmdguardar.setText("Guardar");
        cmdguardar.setEnabled(false);
        cmdguardar.setFocusable(false);
        cmdguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdguardar);

        cmdcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Cancel (2).png"))); // NOI18N
        cmdcancelar.setText("Cancelar");
        cmdcancelar.setEnabled(false);
        cmdcancelar.setFocusable(false);
        cmdcancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdcancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdcancelar);

        cmdeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/page_edit.png"))); // NOI18N
        cmdeditar.setText("Editar");
        cmdeditar.setFocusable(false);
        cmdeditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdeditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdeditar);

        cmdsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/door_in.png"))); // NOI18N
        cmdsalir.setText("Salir");
        cmdsalir.setAlignmentX(100.0F);
        cmdsalir.setFocusable(false);
        cmdsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsalirActionPerformed(evt);
            }
        });
        jToolBar1.add(cmdsalir);

        tblusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CONTRASEÑA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblusuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblusuario);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        txtusuario.setEnabled(false);

        txtpass.setEnabled(false);

        jLabel3.setText("Confirmar contraseña");

        txtpass2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpass)
                            .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("REGISTRO DE USUARIOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 private void Limpiar(){
     txtusuario.setText("");
     txtpass.setText("");
     txtpass2.setText("");
 }
    private void cmdnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdnuevoActionPerformed
        // TODO add your handling code here:

//        //accion: 1 insert , 2 uupdate
        Limpiar();
        accion=1;
        EstadoBotones(false);
        txtusuario.requestFocus();
    }//GEN-LAST:event_cmdnuevoActionPerformed
   private void EstadoBotones(boolean estado){
        
    cmdnuevo.setEnabled(estado);
    cmdcancelar.setEnabled(!estado);
    cmdguardar.setEnabled(!estado);
    cmdeditar.setEnabled(estado);
    cmdsalir.setEnabled(estado);
//    
    txtusuario.setEnabled(!estado);
    txtpass.setEnabled(!estado);
    txtpass2.setEnabled(!estado);
    tblusuario.setEnabled(estado);
//    txtCantidadVendida.setEnabled(!estado);
   
        
    }
    private void cmdguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdguardarActionPerformed
        // TODO add your handling code here:
            
        String pass1=String.valueOf(txtpass.getPassword());
        String pass2=String.valueOf(txtpass2.getPassword());
        
        if (!pass1.equals(pass2)) {
             JOptionPane.showMessageDialog(rootPane, "Las contraseñas no coinciden", "Registro de usuarios", JOptionPane.ERROR_MESSAGE, frameIcon);
             return;
        }
        
        if (accion==1) {
//
            Usuario usuario=new Usuario();
            usuario.setNombre(txtusuario.getText());
            usuario.setContraseña(String.valueOf(txtpass.getPassword()));

           UsuarioService usuarioservice=new UsuarioServiceImpl();
            usuarioservice.crear(usuario);
            JOptionPane.showMessageDialog(rootPane, "Usuario registrado Correctamente", "Registro de categoria", JOptionPane.INFORMATION_MESSAGE, frameIcon);
            EstadoBotones(true);
            Limpiar();
            ListarUsuarios();

        }else if (accion==2){
            int fila=tblusuario.getSelectedRow();
            Usuario usuario=new Usuario();
            usuario.setIdusuario(Integer.parseInt( tblusuario.getValueAt(fila,0).toString()));
            usuario.setNombre(txtusuario.getText());
            usuario.setContraseña(String.valueOf(txtpass.getPassword()));

            UsuarioService usuarioservice=new UsuarioServiceImpl();
            usuarioservice.update(usuario);
            JOptionPane.showMessageDialog(rootPane, "Usuario actualizado correctamente", "Registro de cliente", JOptionPane.INFORMATION_MESSAGE, frameIcon);

            Limpiar();
             ListarUsuarios();;

        }
    }//GEN-LAST:event_cmdguardarActionPerformed
private void ListarUsuarios(){
          DefaultTableModel dtm = (DefaultTableModel) tblusuario.getModel();
        //si esta llena la tabla se borra
        if (tblusuario.getRowCount()>0) {
            
                for (int i = tblusuario.getRowCount() - 1; i >= 0; i--) {
                dtm.removeRow(i);
             }
            
        }
        
        TableColumn tc=tblusuario.getColumnModel().getColumn(2);
        tc.setCellEditor(new DefaultCellEditor(new JPasswordField()));
        ClaveRender cr=new ClaveRender();
        tc.setCellRenderer(cr);
        
        UsuarioService usuarioservice = new UsuarioServiceImpl();
        List<Usuario> usuarios = usuarioservice.listar();
         for (Integer count = 0; count < usuarios.size(); count++){
             dtm.addRow(new Object[]{
                usuarios.get(count).getIdusuario(),
                usuarios.get(count).getNombre(),
                usuarios.get(count).getContraseña()
            });
             
         }
    }
    private void cmdcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcancelarActionPerformed
        // TODO add your handling code here:
        EstadoBotones(true);
    }//GEN-LAST:event_cmdcancelarActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
        // TODO add your handling code here:

//        //accion: 1 insert , 2 uupdate
        accion=2;
        EstadoBotones(false);
    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdsalirActionPerformed

    private void tblusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblusuarioMouseClicked
        // TODO add your handling code here:
        
        if (tblusuario.isEnabled()) {
        int fila=tblusuario.getSelectedRow();
        txtusuario.setText(tblusuario.getValueAt(fila,1).toString());
        txtpass.setText(tblusuario.getValueAt(fila,2).toString());
        txtpass2.setText(tblusuario.getValueAt(fila,2).toString());
        }
         
    }//GEN-LAST:event_tblusuarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdcancelar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdguardar;
    private javax.swing.JButton cmdnuevo;
    private javax.swing.JButton cmdsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblusuario;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JPasswordField txtpass2;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
